const products = [
    {
        id:1,
        name:'ARRI ALEXA LF or MINI LF',
        price:2500.00,
        description:'"Una camara muy bonita que graba en 4K 60fps"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1653433855/img/ALEXA-Mini-LF-SP-47-MVF-2-left-front-white_a6zfrt.jpg',
        stock:5,
        category:'camera',
    },
    {
        id:2,
        name:'PANASONIC VARICAM LT',
        price:450.00,
        description:'"Una camara muy bonita que graba en 4K 60fps"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1653433873/img/Panasonic-Varicam_qhixdc.jpg',
        stock:3,
        category:'camera',
    },
    {
        id:3,
        name:'ARRI ALEXA MINI CAMERA 4:3 ARRIRAW',
        price:875.00,
        description:'"Una camara muy bonita que graba en 4K 60fps"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1653433863/img/Arri-Alexa-Mini-PL-1_y1dzww.jpg',
        stock:14,
        category:'camera',
    },
    {
        id:4,
        name:'Cooke 40mm miniS4/i Lens T2.8',
        price:580.00,
        description:'"Un lente perfecto, para una toma perfecta"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1654299828/img/Cooke40mm_gjc7qf.jpg',
        stock:57,
        category:'lense',
    },
    {
        id:5,
        name:'Cooke S4/i 50mm, T2.0 Prime Lens',
        price:940.00,
        description:'"Un lente perfecto, para una toma perfecta"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1654304149/img/Cooke50mm_z3vwt1.jpg',
        stock:36,
        category:'lense',
    },
    {
        id:6,
        name:'Cooke 100mm miniS4/i Lens T2.8',
        price:1200.00,
        description:'"Un lente perfecto, para una toma perfecta"',
        image: 'https://res.cloudinary.com/itsdanielmx/image/upload/v1654299812/img/Cooke100mm_mbkfwh.jpg',
        stock:23,
        category:'lense',
    }
]
export default products